Repository creativeplatform/crtv3, pull requests merged in 2024-12, with the labels that each got.

#80 Dev
  .env.sample
  .nvmrc
  app/api/auth/thirdweb/auth.ts
  app/api/auth/thirdweb/authentication.ts
  app/api/auth/thirdweb/gateCondition.ts
  app/api/auth/thirdweb/thirdweb.ts
  app/api/livepeer/actions.ts
  app/api/livepeer/audio-to-text/route.ts
  app/api/livepeer/audioToText.ts
  app/api/livepeer/livepeerActions.ts
  app/api/livepeer/livepeerAiActions.ts
  app/api/livepeer/textToImage.ts
  app/api/livepeer/token-gate/route.ts
  app/api/livepeer/translate.ts
  app/api/livepeer/translation/route.ts
  app/components/Button/actions/login.ts
  app/components/Button/connectButton.tsx
  app/components/Button/connectButtonWrapper.tsx
  app/components/Layout/Navbar.tsx
  app/components/Layout/userMenu.tsx
  app/components/Paywall/ClaimLock.tsx
  app/components/Player/Player.tsx
  app/components/Player/SimplePlayer.tsx
  app/components/Player/Subtitles.tsx
  app/components/Player/VideoJSPlayer.tsx
  app/components/Player/VideoPlayer.tsx
  app/components/Videos/Detail/Detail.tsx
  app/components/Videos/Upload/Create-info.tsx
  app/components/Videos/Upload/Create-thumbnail.tsx
  app/components/Videos/Upload/CreateThumbnailForm.tsx
  app/components/Videos/Upload/FileUpload.tsx
  app/components/Videos/Upload/PreviewVideo.tsx
  app/components/Videos/Upload/index.tsx
  app/components/Videos/VideoCard.tsx
  app/components/Videos/VideoCardGrid.tsx
  app/components/Videos/VideoDetails.tsx
  app/lib/access-key.ts
  app/lib/sdk/livepeer/aiClient.ts
  app/lib/sdk/orbisDB/client.ts
  app/lib/sdk/orbisDB/context.tsx
  app/lib/sdk/orbisDB/models/AssetMetadata.ts
  app/lib/types.ts
  app/lib/utils/context.ts
  app/lib/utils/hooks/useAllPlaybackSources.ts
  app/lib/utils/hooks/useCreateAsset.ts
  app/lib/utils/hooks/useDetailPlaybackSources.ts
  app/lib/utils/hooks/useFeaturePlaybackSource.ts
  app/lib/utils/hooks/useHeroPlaybackSource.ts
  app/lib/utils/scripts/createOrbisDbModels.ts
  app/providers.tsx
  package-lock.json
  package.json
Labels: enhancement

#84 Thumnail bug fix
  app/api/livepeer/audioToText.ts
  app/api/livepeer/livepeerAiActions.ts
  app/api/livepeer/textToImage.ts
  app/components/Videos/Upload/CreateThumbnailForm.tsx
  app/components/Videos/Upload/FileUpload.tsx
  package-lock.json
  package.json
Labels: hotfix

#83 Subtitles bugfix
  app/api/auth/thirdweb/authentication.ts
  app/api/livepeer/actions.ts
  app/api/livepeer/audio-to-text/route.ts
  app/api/livepeer/audioToText.ts
  app/api/livepeer/livepeerActions.ts
  app/api/livepeer/token-gate/route.ts
  app/api/livepeer/translate.ts
  app/api/livepeer/translation/route.ts
  app/components/Player/Player.tsx
  app/components/Player/Subtitles.tsx
  app/components/Videos/Upload/Create-info.tsx
  app/components/Videos/Upload/FileUpload.tsx
  app/components/Videos/Upload/index.tsx
  app/components/Videos/VideoDetails.tsx
  app/lib/access-key.ts
  app/lib/sdk/orbisDB/context.tsx
  app/providers.tsx
Labels: hotfix

#81 Swimm: batch commit 2 files
  .swm/claiming-your-creative-pass.wqwihjd7.sw.md
  .swm/connecting-to-the-app.jcojvvx2.sw.md
  .swm/dev-environment-setup.7hiasa10.sw.md
  .swm/setting-up-metokens.zr4b2buq.sw.md
  .swm/start-here.6ixy1lke.pl.sw.md
  .swm/swimm.json
  .swm/uploading-videos.8uqmz2sy.sw.md
  .swm/user-docs.pati60ca.sw.md
Labels: documentation

#85 Subtitles bugfix
  .env.sample
  app/api/livepeer/audioToText.ts
  app/api/livepeer/translation/route.ts
  app/components/Player/Player.tsx
  app/components/Videos/Upload/Create-thumbnail.tsx
  app/lib/sdk/orbisDB/context.tsx
Labels: hotfix

#89 Latest Docs
  .swm/claiming-your-creative-pass.wqwihjd7.sw.md
  .swm/connecting-to-the-app.jcojvvx2.sw.md
  .swm/dev-environment-setup.7hiasa10.sw.md
  .swm/setting-up-metokens.zr4b2buq.sw.md
  .swm/start-here.6ixy1lke.pl.sw.md
  .swm/swimm.json
  .swm/uploading-videos.8uqmz2sy.sw.md
  .swm/user-docs.pati60ca.sw.md
Labels: documentation

#105 Avatar updates
  .codeiumignore
  app/components/Layout/Navbar.tsx
  app/components/UserProfile/MemberCard.tsx
  app/components/UserProfile/UserProfile.tsx
  app/components/Videos/Upload/FileUpload.tsx
  app/components/Videos/Upload/index.tsx
  app/components/Videos/VideoCard.tsx
  app/components/Videos/VideoCardGrid.tsx
  app/components/home-page/TopChart.tsx
  app/lib/sdk/stack/client.ts
  app/lib/utils/context.ts
  next.config.js
  package-lock.json
  package.json
Labels: enhancement, hotfix

#106 Dev
  .codeiumignore
  app/components/Layout/Navbar.tsx
  app/components/UserProfile/MemberCard.tsx
  app/components/UserProfile/UserProfile.tsx
  app/components/Videos/Upload/FileUpload.tsx
  app/components/Videos/Upload/index.tsx
  app/components/Videos/VideoCard.tsx
  app/components/Videos/VideoCardGrid.tsx
  app/components/home-page/TopChart.tsx
  app/lib/sdk/stack/client.ts
  app/lib/utils/context.ts
  next.config.js
  package-lock.json
  package.json
Labels: enhancement

#108 Dev
  app/components/Button/connectButtonWrapper.tsx
  app/components/home-page/TopChart.tsx
  package-lock.json
  package.json
Labels: hotfix
